
server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_contacts
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false

app:
  jwtSecret: JWTSuperSecretKey
  tokenValidHours: 20






