
server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users_contacts?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#<<<<<<< Updated upstream
#    username: root
#    password: root1234
#=======
    username: root
    password: root
#>>>>>>> Stashed changes
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


app:
  jwtSecret: JWTSuperSecretKey
  tokenValidHours: 20






